[package]
name = "tenant"
version = "0.1.0"
edition = "2024"

[dependencies]
async-stream = "0.3.6"
bytes = "1.10.1"
futures = "0.3.31"
hyper = { version = "1.7.0", features = ["full"] }
opencv = { version = "0.97.0" }
reqwest = "0.12.24"
tokio = { version = "1.48.0", features = ["full"] }
